-- Ajouter les nouveaux champs à email_templates
ALTER TABLE email_templates 
ADD COLUMN IF NOT EXISTS text_content TEXT,
ADD COLUMN IF NOT EXISTS last_test_sent_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS last_test_sent_to TEXT,
ADD COLUMN IF NOT EXISTS legal_review_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS legal_review_by UUID,
ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1;

-- Mettre à jour les templates existants avec du contenu plus professionnel
UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;padding:0;background:#f5f5f5}.container{max-width:700px;margin:0 auto;background:#fff}.header{background:linear-gradient(135deg,#0ea5e9,#0284c7);color:#fff;padding:30px 40px;text-align:center}.header h1{margin:0;font-size:24px}.body{padding:40px}.section{margin:25px 0;padding:20px;background:#f8fafc;border-radius:12px}.section h2{margin:0 0 15px;font-size:16px;color:#1e293b}.data-row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e2e8f0}.data-label{color:#64748b}.data-value{font-weight:600;color:#1e293b}.legal{background:#fafafa;padding:25px 40px;font-size:11px;color:#666;border-top:1px solid #e2e8f0}.legal p{margin:5px 0}.footer{background:#1e293b;color:#94a3b8;padding:25px 40px;text-align:center;font-size:12px}.footer a{color:#60a5fa}</style></head><body><div class="container"><div class="header"><h1>🧾 Facture {{invoiceNumber}}</h1><p>Date: {{invoiceDate}}</p></div><div class="body"><div class="section"><h2>Émetteur</h2><p><strong>{{companyName}}</strong><br>{{companyAddress}}<br>SIRET: {{companySiret}} | RCS: {{companyRCS}}<br>TVA: {{companyTVA}} | Capital: {{companyCapital}}</p></div><div class="section"><h2>Client</h2><p><strong>{{customerName}}</strong><br>{{customerAddress}}<br>{{customerEmail}}</p></div><div class="section"><h2>Détails</h2>{{itemsHtml}}<div class="data-row" style="border-top:2px solid #0ea5e9;margin-top:15px;padding-top:15px"><span class="data-label">Total TTC</span><span class="data-value" style="color:#0ea5e9;font-size:18px">{{totalTTC}} €</span></div></div></div><div class="legal"><p><strong>Mentions légales:</strong> En cas de retard, pénalité de 3x le taux légal + 40€ de frais de recouvrement (Art. L441-10 et D441-5 Code commerce). Pas d''escompte. Tribunal compétent: {{companyJuridiction}}.</p></div><div class="footer"><p>{{companyName}} - {{companyAddress}}</p><p>SIRET {{companySiret}}</p></div></div></body></html>',
  variables = '["invoiceNumber","invoiceDate","dueDate","companyName","companyAddress","companySiret","companyRCS","companyTVA","companyCapital","companyJuridiction","companyEmail","companyPhone","customerName","customerAddress","customerEmail","itemsHtml","subtotalHT","tvaRate","tvaAmount","totalTTC","paymentMethod","paymentStatus"]'::jsonb,
  description = 'Facture conforme aux obligations légales françaises',
  updated_at = now()
WHERE template_key = 'invoice';

UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:linear-gradient(135deg,#0ea5e9,#0284c7);color:#fff;padding:40px;text-align:center}.header h1{margin:0 0 10px}.body{padding:40px}.plan-card{background:linear-gradient(135deg,#0ea5e9,#0284c7);color:#fff;border-radius:12px;padding:25px;text-align:center;margin:25px 0}.plan-name{font-size:24px;font-weight:bold}.plan-price{font-size:36px;font-weight:bold}.section{background:#f8fafc;border-radius:12px;padding:25px;margin:25px 0}.section h2{margin:0 0 15px;font-size:16px;color:#64748b}.data-row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e2e8f0}.legal{background:#fafafa;padding:25px 40px;font-size:12px;color:#64748b;border-top:1px solid #e2e8f0}.legal h3{font-size:14px;color:#1e293b;margin:15px 0 10px}.footer{background:#1e293b;color:#94a3b8;padding:30px 40px;text-align:center;font-size:12px}.footer a{color:#60a5fa}.cta{display:inline-block;background:#0ea5e9;color:#fff;padding:15px 35px;text-decoration:none;border-radius:8px;font-weight:bold;margin:20px 0}</style></head><body><div class="container"><div class="header"><div style="font-size:60px">✅</div><h1>Abonnement confirmé!</h1></div><div class="body"><p>Bonjour <strong>{{firstName}}</strong>,</p><p>Votre abonnement ANR est maintenant actif!</p><div class="plan-card"><div class="plan-name">{{planName}}</div><div class="plan-price">{{planPrice}} € <span style="font-size:16px">/ {{billingCycle}}</span></div></div><div class="section"><h2>Récapitulatif</h2><div class="data-row"><span>N° commande</span><span>{{subscriptionId}}</span></div><div class="data-row"><span>Date</span><span>{{startDate}}</span></div><div class="data-row"><span>Prochaine échéance</span><span>{{nextBillingDate}}</span></div><div class="data-row"><span>Code ANR</span><span>{{anrCode}}</span></div></div><div style="text-align:center"><a href="{{dashboardUrl}}" class="cta">Accéder à mon espace</a></div></div><div class="legal"><h3>Droit de rétractation</h3><p>Conformément à l''Art. L221-18, vous disposez de 14 jours pour vous rétracter. Date limite: {{retractationDeadline}}.</p><h3>Résiliation</h3><p>Résiliez à tout moment depuis votre espace client. <a href="{{cancellationUrl}}">Gérer mon abonnement</a></p></div><div class="footer"><p>ANR - {{companyName}}</p><p><a href="{{cguUrl}}">CGU</a> | <a href="{{privacyUrl}}">Confidentialité</a></p></div></div></body></html>',
  variables = '["firstName","lastName","email","planName","planPrice","billingCycle","subscriptionId","startDate","nextBillingDate","anrCode","anrAddress","dashboardUrl","retractationDeadline","cancellationUrl","cguUrl","privacyUrl","companyName"]'::jsonb,
  description = 'Confirmation d''abonnement avec mentions légales et droit de rétractation',
  updated_at = now()
WHERE template_key = 'subscription_confirmation';

UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{background:linear-gradient(135deg,#0ea5e9,#0284c7);color:#fff;padding:40px;text-align:center}.body{padding:40px}.invite-card{background:linear-gradient(135deg,#f0f9ff,#e0f2fe);border:2px solid #0ea5e9;border-radius:16px;padding:30px;margin:25px 0;text-align:center}.invite-card h2{color:#0369a1;margin:0 0 15px}.habitation-name{font-size:28px;font-weight:bold;color:#1e293b}.address{color:#64748b}.cta{display:inline-block;background:#0ea5e9;color:#fff;padding:18px 45px;text-decoration:none;border-radius:10px;font-weight:bold;font-size:18px;margin:25px 0}.warning{background:#fef3c7;border-left:4px solid #f59e0b;padding:15px 20px;margin:25px 0}.footer{background:#1e293b;color:#94a3b8;padding:30px 40px;text-align:center;font-size:12px}.footer a{color:#60a5fa}</style></head><body><div class="container"><div class="header"><div style="font-size:50px">🏠</div><h1>Vous êtes invité(e)!</h1></div><div class="body"><p>Bonjour <strong>{{recipientFirstName}}</strong>,</p><p>Vous avez été invité(e) à rejoindre une habitation sur ANR.</p><div class="invite-card"><h2>🏡 Habitation</h2><div class="habitation-name">{{habitationName}}</div><div class="address">📍 {{habitationAddress}}</div><p style="margin-top:15px;color:#0369a1;font-weight:bold">Code ANR: {{anrCode}}</p><p>Invité par <strong>{{inviterName}}</strong></p></div><div style="text-align:center"><a href="{{invitationUrl}}" class="cta">✅ Accepter l''invitation</a></div><div class="warning"><strong>⏰ Expire le {{expirationDate}}</strong></div></div><div class="footer"><p>ANR - Adresse Numérique Résidentielle</p><p><a href="mailto:{{supportEmail}}">{{supportEmail}}</a></p></div></div></body></html>',
  variables = '["recipientFirstName","recipientEmail","inviterName","inviterEmail","habitationName","habitationAddress","anrCode","invitationUrl","expirationDate","supportEmail","cguUrl","privacyUrl"]'::jsonb,
  description = 'Invitation à rejoindre une habitation ANR',
  updated_at = now()
WHERE template_key = 'resident_invitation';

UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;background:#f5f5f5}.container{max-width:700px;margin:0 auto;background:#fff}.header{background:linear-gradient(135deg,#8b5cf6,#7c3aed);color:#fff;padding:40px;text-align:center}.legal-banner{background:#f0fdf4;border-left:4px solid #22c55e;padding:20px}.body{padding:40px}.section{margin:30px 0}.section h2{margin:0 0 15px;font-size:18px;color:#1e293b;border-bottom:2px solid #e2e8f0;padding-bottom:10px}.data-table{width:100%;border-collapse:collapse}.data-table th{background:#f8fafc;padding:12px;text-align:left;font-size:12px;color:#64748b}.data-table td{padding:12px;border-bottom:1px solid #e2e8f0}.rights-box{background:#faf5ff;border-radius:12px;padding:25px;margin:30px 0}.dpo-box{background:#1e293b;color:#fff;padding:25px;border-radius:12px;margin:30px 0}.dpo-box a{color:#60a5fa}.cnil-box{background:#fef3c7;border-left:4px solid #f59e0b;padding:20px;margin:25px 0}.footer{background:#1e293b;color:#94a3b8;padding:30px 40px;text-align:center;font-size:12px}</style></head><body><div class="container"><div class="header"><div style="font-size:50px">🔒</div><h1>Export de vos données personnelles</h1><p>Conformément au RGPD - Article 15</p></div><div class="legal-banner"><p><strong>Droit d''accès exercé le {{requestDate}}</strong> - Conformément à l''article 15 du RGPD (UE 2016/679), voici l''ensemble de vos données personnelles.</p></div><div class="body"><div class="section"><h2>👤 Données d''identité</h2><table class="data-table"><tr><td>Nom</td><td>{{lastName}}</td></tr><tr><td>Prénom</td><td>{{firstName}}</td></tr><tr><td>Email</td><td>{{email}}</td></tr><tr><td>Téléphone</td><td>{{phone}}</td></tr><tr><td>Inscription</td><td>{{createdAt}}</td></tr></table></div><div class="rights-box"><h3>📋 Vos droits RGPD</h3><p>✏️ <strong>Rectification (Art. 16)</strong> - Corriger vos données</p><p>🗑️ <strong>Effacement (Art. 17)</strong> - Supprimer vos données</p><p>⏸️ <strong>Limitation (Art. 18)</strong> - Limiter le traitement</p><p>📤 <strong>Portabilité (Art. 20)</strong> - Récupérer vos données</p><p>🚫 <strong>Opposition (Art. 21)</strong> - Vous opposer au traitement</p></div><div class="dpo-box"><h3>👤 Délégué à la Protection des Données</h3><p>📧 <a href="mailto:{{dpoEmail}}">{{dpoEmail}}</a></p><p>📍 {{companyAddress}}</p></div><div class="cnil-box"><strong>⚖️ Réclamation CNIL</strong><p>Si vos droits ne sont pas respectés: <a href="https://www.cnil.fr/fr/plaintes">www.cnil.fr/fr/plaintes</a></p></div></div><div class="footer"><p>{{companyName}} - SIRET {{companySiret}}</p><p>Document généré le {{exportDate}}</p></div></div></body></html>',
  variables = '["firstName","lastName","email","phone","createdAt","lastLoginAt","habitations","subscriptions","callHistory","devices","consents","downloadUrl","requestDate","exportDate","dpoEmail","companyName","companyAddress","companySiret"]'::jsonb,
  description = 'Export RGPD complet conforme à l''article 15 avec droits et contact DPO',
  updated_at = now()
WHERE template_key = 'rgpd_export';

UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;background:#f5f5f5}.container{max-width:700px;margin:0 auto;background:#fff}.header{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff;padding:30px}.header h1{margin:0;font-size:22px}.priority-high{background:#fef2f2;color:#991b1b;border-left:4px solid #ef4444;padding:15px 30px}.priority-medium{background:#fffbeb;color:#92400e;border-left:4px solid #f59e0b;padding:15px 30px}.priority-low{background:#f0fdf4;color:#166534;border-left:4px solid #22c55e;padding:15px 30px}.body{padding:30px}.user-card{background:#f8fafc;border-radius:12px;padding:20px;margin-bottom:25px}.messages-section{margin:25px 0}.message{padding:15px;margin:10px 0;border-radius:8px}.message-user{background:#f0f9ff;border-left:3px solid #0ea5e9}.message-bot{background:#f5f3ff;border-left:3px solid #8b5cf6}.cta{display:inline-block;background:#ef4444;color:#fff;padding:15px 35px;text-decoration:none;border-radius:8px;font-weight:bold;margin:20px 0}.footer{background:#1e293b;color:#94a3b8;padding:25px 30px;text-align:center;font-size:12px}</style></head><body><div class="container"><div class="header"><h1>🎧 Nouvelle demande de support</h1><p>Ticket #{{conversationId}}</p></div><div class="priority-{{priorityClass}}">Priorité: {{priority}}</div><div class="body"><div class="user-card"><h3>👤 Utilisateur</h3><p><strong>{{userName}}</strong><br>{{userEmail}}<br>{{userPhone}}</p></div><div class="messages-section"><h3>💬 Conversation</h3>{{messagesHtml}}</div><div style="text-align:center"><a href="{{adminUrl}}" class="cta">📋 Traiter la demande</a></div></div><div class="footer"><p>Notification automatique - Ne pas répondre à cet email</p></div></div></body></html>',
  variables = '["conversationId","userName","userEmail","userPhone","createdAt","lastMessageAt","messageCount","messagesHtml","priority","priorityClass","adminUrl"]'::jsonb,
  description = 'Notification de nouvelle demande de support pour l''équipe',
  updated_at = now()
WHERE template_key = 'support_notification';

UPDATE email_templates SET 
  html_content = '<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;line-height:1.6;color:#1a1a1a;margin:0;background:#f5f5f5}.container{max-width:600px;margin:0 auto;background:#fff}.header{padding:40px;text-align:center}.header-created{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff}.header-updated{background:linear-gradient(135deg,#f59e0b,#d97706);color:#fff}.header-deleted{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff}.body{padding:40px}.access-card{background:linear-gradient(135deg,#f0f9ff,#e0f2fe);border:2px solid #0ea5e9;border-radius:16px;padding:25px;margin:25px 0}.access-detail{display:flex;align-items:flex-start;gap:12px;padding:12px;background:#fff;border-radius:8px;margin:10px 0}.grantor-info{background:#fafafa;border-radius:12px;padding:20px;margin:25px 0}.instructions{background:#fef3c7;border-left:4px solid #f59e0b;padding:20px;margin:25px 0}.footer{background:#1e293b;color:#94a3b8;padding:30px 40px;text-align:center;font-size:12px}.footer a{color:#60a5fa}</style></head><body><div class="container"><div class="header header-{{actionClass}}"><div style="font-size:50px">{{actionIcon}}</div><h1>{{actionLabel}}</h1><p>Accès "{{accessName}}"</p></div><div class="body"><p>Bonjour <strong>{{beneficiaryName}}</strong>,</p><p>{{actionDescription}}</p><div class="access-card"><h2 style="color:#0369a1;margin:0 0 20px;text-align:center">🔐 Détails</h2><div class="access-detail">🏠 <strong>Adresse:</strong> {{address}}</div><div class="access-detail">📅 <strong>Jours:</strong> {{days}}</div><div class="access-detail">🕐 <strong>Horaires:</strong> {{timeFrom}} - {{timeTo}}</div><div class="access-detail">📆 <strong>Validité:</strong> {{validFrom}} au {{validUntil}}</div></div><div class="grantor-info"><p>Accordé par <strong>{{grantorName}}</strong><br>📞 {{grantorPhone}}</p></div>{{#if instructions}}<div class="instructions"><strong>📝 Instructions:</strong><br>{{instructions}}</div>{{/if}}</div><div class="footer"><p>ANR - <a href="mailto:{{supportEmail}}">{{supportEmail}}</a></p></div></div></body></html>',
  variables = '["actionLabel","actionClass","actionIcon","actionDescription","accessName","beneficiaryName","address","days","timeFrom","timeTo","validFrom","validUntil","grantorName","grantorPhone","instructions","supportEmail"]'::jsonb,
  description = 'Notification de création/modification/suppression d''accès programmé',
  updated_at = now()
WHERE template_key = 'scheduled_access_notification';